### ISSUE TITLE
Eliminate the GPL file from CORE packages and provide it separately

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/bugz#104]
Many CORE packages are still GPL software. Replacing them all with software under a healthier license is not realistic, but at least it should be possible to remove the license file from all these packages and replace it with a single package `GPL2.SVP` that would install the GPLv2 license into `%DOC%\GPL2.TXT` so it's available one time for all packages that refer to it.
The goal being to limit the footprint of an installed SvarDOS system. The GPL2 license is 18K big. It's quite wasteful to duplicate it for every package, esp. considering that the tools are most of the time smaller than their license file: ATTRIB (5K), DELTREE (3K), FC (15K), MEM (14K), MOVE (15K)...

**Comment by boeckmann** [comment]
I think this is a very good idea! FDISK also contains a copy of it.

**Comment by mateuszviste** [comment]
Done.

> I think this is a very good idea! FDISK also contains a copy of it.

Indeed.

I also noticed that the KERNLEDR package contains directory entries (ie. empty entries like "DOC/", "BIN/", etc). These are useless and only take space (only few hundreds of bytes, but still).
````
unzip -l kernledr.svp
Archive:  kernledr.svp
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2024-08-12 19:49   appinfo/
      112  2024-08-12 19:49   appinfo/kernledr.lsm
        0  2024-08-12 19:49   bin/
    14596  2024-08-12 19:49   bin/country.sys
        0  2024-08-12 19:49   doc/
     4073  2024-08-12 19:49   doc/license.htm
    60617  2024-08-12 19:49   kernel.sys
---------                     -------
    79398                     7 files
````

Is it possible to eliminate them from the github-built package? Do not worry if this is complicated, but if it is just a matter of adding a zip command then the best way to compress a package with infozip is `zip -9rkDX kernledr.svp kernel.sys appinfo bin doc`

I also like to do a `advzip -z -4 -i 1000 kernledr.svp` afterwards to squeeze out a couple of percents, but this requires to have advzip installed, so probably not as easy as just an extra infozip flag.
