### ISSUE TITLE
New SYS repo

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/bugz#110]
I am in the process of refactoring out the SYS command from the kernel into its own repo and make a few adjustments, can we make a repo for it here?

**Comment by mateuszviste** [comment]
Sure thing. Do you prefer to store it in svn, along with the rest of SvarDOS, or have a dedicated github repo like with EDR?

**Comment by boeckmann** [comment]
Good question. I am tempted to put this under SVN :)

**Comment by mateuszviste** [comment]
> Good question. I am tempted to put this under SVN :)

You're welcome to - just create a directory at the root and do your thing. svn is so much cooler than git. Once you have something I will add it as a web subproject so it has its own simple webpage, like [SvarCOM](http://www.svardos.org/svarcom/), [Sved](http://www.svardos.org/sved/) and [wmincrt](http://www.svardos.org/wmincrt/).

Should you change your mind later and prefer to switch to git(hub) for whatever reason, that's fine as well - either create the repo yourself (you should have all the necessary rights to the SvarDOS account) or let me know and I will do the necessary clicking. :)
