### ISSUE TITLE
Flag EDR branch as stable

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/bugz#118]
The EDR branch ("bleeding edge") seems to be very stable. I tested it on several VMs, as well as 4 real PCs from different eras (80C88, 286, 386, Pentium II) and did not have any issues.

The installer also appears to be perfectly functional.

I will do a couple of last tests installing SvarDOS on a few VM setups and if nothing pops out I will flag [20240905](http://svardos.org/?p=files&dir=20240905) as the new "stable" SvarDOS in a day or two.

**Comment by boeckmann** [comment]
I yesterday got a report from Willi Spiegl that the  installer from 20240824 seems to have problems installing on FAT32 partitions. We should check this with the current version before flagging it stable. Can do it today afternoon.

This is what Willi wrote me (on German):

>Ich habe gerade die 1,4 MB Diskettenversion von SvarDOS getestet (siehe Link unten):
>
>Die Installationsroutine kann nicht mit FAT32 umgehen. D.h. wenn die HD auf FAT16 läuft, läuft die Routine durch, bei FAT32 erhalte ich die Meldung:
>
>"Error: No drive could be found. Perhaps your HD needs to be partitioned first. Please create at least one primary partition..."
>
>(fdisk hat die schon erstellt). Wenn ich dann auf "Create a primary partition automatically" gehe, kommt kurz ne Fehlermeldung:
>
>"Error creating a primary partition..."
>
>Das scheint rein ein Problem der Installationsroutine zu sein, denn mit manuellem fdisk FAT32 und format /s gibts keinerlei Probleme.
>
>FAT16 funktioniert und zeigt die Partition an, auf der installiert werden soll. Läuft auch durch.

**Comment by mateuszviste** [comment]
translation below for german-handicaped people like me (courtesy of google translate)

> I have just tested the 1.4 MB floppy disk version of SvarDOS (see link below):
> 
> The installation routine cannot handle FAT32. This means that if the HD is running on FAT16, the routine runs through, but with FAT32 I get the message:
> 
> "Error: No drive could be found. Perhaps your HD needs to be partitioned first. Please create at least one primary partition..."
> 
> (fdisk has already created it). If I then click on "Create a primary partition automatically", an error message appears briefly:
> 
> "Error creating a primary partition..."
> 
> This seems to be purely a problem with the installation routine, because with manual fdisk FAT32 and format /s there are no problems at all.
> 
> FAT16 works and shows the partition on which the installation is to take place. It also runs through.

**Comment by mateuszviste** [comment]
I did not test the installer with FAT32, will do so. Maybe the problem is here:

![image](https://github.com/user-attachments/assets/a3a1a8f0-a32c-4358-a6c7-71745d5a2252)

This is how the installer filters out partitions that SvarDOS can be installed on.

**Comment by mateuszviste** [comment]
partition type "0x0B" is missing - according to the wiki it is for FAT-32 partitions with CHS addressing. So I guess that's what Willy uses.

**Comment by boeckmann** [comment]
Yes, this is likely being the cause. 0x0b is FAT32 with CHS access under MS-DOS 7+. FDISK creates a 0x0b partition if within the 1024 cylinder limit.

**Comment by mateuszviste** [comment]
I have added 0x0B, as well as 0x04, and removed 0x08 (apparently it is a vendor-specific FAT marker from Commodore MS-DOS 3.x, but could also be lots of other things).

New list:

![image](https://github.com/user-attachments/assets/76a46dc8-b185-46a6-a36b-64de067df102)

It is in [build 20240905](http://svardos.org/?p=files&dir=20240905) now. Hopefully this should work better.

**Comment by boeckmann** [comment]
I'll ask Willi to test it again. Great thing about Willi is that he usually finds this kind of bugs :)

Nice color scheme, btw :) How is it called?

**Comment by ecm-pushbx** [comment]
> Yes, this is likely being the cause. 0x0b is FAT32 with CHS access under MS-DOS 7+. FDISK creates a 0x0b partition if within the 1024 cylinder limit.

Nitpick: FAT32, both LBA and CHS, is MS-DOS v7.10+ only.

**Comment by mateuszviste** [comment]
> Nice color scheme, btw :) How is it called?

I use KWrite, the color scheme is the default as preset by my distro - apparently it is called "breeze light". The font is [DOSEGA](https://sourceforge.net/projects/dosega/) (a TTF font that I made 15 years ago, replicating by hand the default VGA font)

**Comment by boeckmann** [comment]
> It is in [build 20240905](http://svardos.org/?p=files&dir=20240905) now. Hopefully this should work better.

Confirmed to have fixed the issue.

**Comment by mateuszviste** [comment]
Thanks for the confirmation (and thanks to Fritz for his tests!). I am closing this issue then.
