### ISSUE TITLE
SvarLANG returns first string when asked for string [0,0] even if such string does not exists

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/bugz#119]
Seen with localcfg. string [0,0] does not exist, yet asking for svalang_strid(0) returns the first available string in the dictionary [0,1]

**Comment by boeckmann** [comment]
I will have a look at his the next days...

**Comment by boeckmann** [comment]
Or is it already fixed (you closed this)?

**Comment by boeckmann** [comment]
fixed by http://svn.svardos.org/comp.php?repname=SvarDOS&compare[]=%2Fsvarlang.lib%2F@2004&compare[]=%2Fsvarlang.lib%2F@2005

**Comment by mateuszviste** [comment]
Works now :-) Thanks!
