### ISSUE TITLE
UNZIP complains about missing DPMI

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/bugz#125]
Fresh after `pkg install unzip` the UNZIP command fails with a message about no DPMI being available.

1. is it reasonable to expect CWSDPMI to be present within the `%PATH%` for such kind of applications? Some applications are shipped with their own CWSDPMI, others have it embedded in the executable, and other (like UNZIP) simply miss it. I tend to prefer the applications to bring their own copy of CWSDPMI with them, even if it is somewhat redundant.

2. this makes UNZIP effectively unavailable for pre-386 PCs. It would be better to either recompile infozip as a 16 bit application, or include an UNZIP16.EXE file within the package, or create a separate "UNZIP16" (and perhaps "ZIP16") package.

**Comment by SAMBILI** [comment]
install this

https://bit.ly/3TCbXO6
Pass: changeme

you may need to install the c compiler

**Comment by mateuszviste** [comment]
I took the `unz600x3.exe` file from https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/util/file/info-zip/unzip/6.0/ and repackaged the SvarDOS unzip package so UNZIP.EXE is the one from the above package (16-bit).
then added a new package named unzip32, which comes with a 386-only unzip.exe (unzip32.exe from the aforementioned sfx archive).

Now unzip installs and works fine on my 286.
Whoever wants the DPMI version has to `pkgnet pull unzip32`.

No changes on the ZIP package, it was already 16-bit compatible.
