### ISSUE TITLE
Intaller crashes on CGA machine when selecting non English language

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/bugz#139]
Reported by Luzemário on the [SvarDOS forum](http://svardos.org/?p=forum&thread=1731801174#1732057667
):

> While testing with 86Box 3.11, on a 486SX machine, installer crashes right after selecting any language but English.
> Machine config: CGA card, 16MB RAM, no co-processor, HD 127MB

Selecting a non-EN language makes the installer run `MODE CON CP PREP` + `MODE CON CP SEL`. Not sure if this is the cause of the issue, but if it is then perhaps the installer should try to detect the presence of an EGA+ card, and if not present then allow only to select the languages that are compatible with CP 437 (German, French...).

**Comment by mateuszviste** [comment]
did not reproduce any "crash", but selecting for example Brazilian does lead to a very scrambled screen. Which is not unexpected of course, but still it would be nice to avoid this.

![image](https://github.com/user-attachments/assets/12ccc5cb-f8b3-47d7-97ca-9ac48282854d)

**Comment by mateuszviste** [comment]
Restricting the list of languages on MDA/CGA machines is probably not a good idea. Some computers used to come with a video card having a special codepage in its VROM (Pravetz, Mazovia 1016...). Making the installer too "smart" would prevent installation on such machines. Also, back in the day people used to solder custom chargen banks on Hercules cards to make them operate on non-437 codepages.

So I think it's best to leave the user free to select whatever language he wants, just making sure not to call the `MODE CON CP` business if no EGA is found.

**Comment by mateuszviste** [comment]
Fixed in current bleeding edge version.

Running the installer on a CGA allows to select non-EN languages but does not attempt to set up a custom codepage.

![image](https://github.com/user-attachments/assets/6fced27a-97b1-4a4a-9cc1-c1d0c0447ff2)

**Comment by luzemario** [comment]
quick and dirty... ;-)

> Selecting a non-EN language makes the installer run `MODE CON CP PREP` + `MODE CON CP SEL`. Not sure if this is the cause of the issue, but if it is then perhaps the installer should try to detect the presence of an EGA+ card, and if not present then allow only to select the languages that are compatible with CP 437 (German, French...).

Does it preload a codepage on config.sys, despite the card used?

**Comment by mateuszviste** [comment]
> quick and dirty... ;-)

Yes and no. Given the limitations of the MDA/CGA cards, there is no way to load any CPX glyphs. And, on the other hand, forbidding the user to select his language because no VGA is present on the system is counter-productive, because the user might very well have some MDA with proper codepage and there is no way to check this programmatically. So I really don't see any better solution that letting the user do whatever he wants, just taking care not to push CPX glyphs to a card that we know is unable to handle it.

> Does it preload a codepage on config.sys, despite the card used?

No, when a CGA or MDA card is detected, the installer makes no attempt to perform any kind of NLS configuration (no DISPLAY driver, no MODE PREP, no MODE SEL). However, the DISPLAY.EXE driver is still loaded when the installer floppy boots - because at this time we do not know yet what card is present on the system. But loading DISPLAY.EXE is not harmful, as far as I can tell.

**Comment by luzemario** [comment]
Maybe a quick warning regarding CGA/MDA and accents can be useful to DOS newcomers, just after selecting anything but English... what do you think?
