### ISSUE TITLE
INSTALL.LST is missing in svardos-20241125-usb.zip

### ISSUE THREAD

**Issue by guidol70** [SvarDOS/bugz#145]
After formatting the drive the install stops, because IMSTALL.LST is missing in the 
USB-Image svardos-20241125-usb.zip

The INSTALL.LST from the CD-Image svardos-20241125-cd.zip isnr compatible,
because after package 32 of 34 its asks for a 2nd floppy-disc ;)

So I extracted BOOT.IMG out of the CD-Image and flashed it (because Etcher wont do it)  
via the "USB Image Tool" (https://www.alexpage.de/usb-image-tool/) to a USB-Stick.
That worked fine for the install.

**Comment by mateuszviste** [comment]
Hello Guido, thank you for your detailed report. I think that [build 20241230](http://svardos.org/?p=files&dir=20241230) should fix this (at least I see with a hex editor that a proper INSTALL.LST is being added to the USB image now). Please let me know if anything else is broken for you.
