### ISSUE TITLE
PATH= not working

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/bugz#150]
When setting the PATH via `PATH=` either from batch of from command line, SvarCOM throws a _file or directory not found_ error. However, this should work, as several installers put it into `autoexec.bat` this way, and it is also supported by MS COMMAND.COM.

<img width="329" alt="Bildschirmfoto 2024-12-31 um 12 41 34" src="https://github.com/user-attachments/assets/d61c9170-4442-4b85-9713-4854424bb470" />

**Comment by mateuszviste** [comment]
PATH=???? is not recognized as an internal command, so SvarCOM tries to match it to an external command, but finds none. I did no know such syntax exists. I confirm that MS-DOS 5.0 supports it all right.

![image](https://github.com/user-attachments/assets/096d8f45-3852-443f-97a6-a833f57119e3)

**Comment by boeckmann** [comment]
For example Borland C++ 4.5 installer puts it this way into autoexec.bat.

**Comment by mateuszviste** [comment]
It definitely works, yes, even though it is not documented:

![image](https://github.com/user-attachments/assets/54e2b1d5-2e0b-4ce1-acfc-69cdf6726621)

It seems this goes well beyond "PATH". The equal sign appears to be considered as a white space:

![image](https://github.com/user-attachments/assets/fb3eef13-8d02-4dbe-b353-28cc6709feee)

That's a good news I guess, as it should be simpler to implement it that way.

**Comment by mateuszviste** [comment]
Committed a fix https://github.com/SvarDOS/core/commit/eefeb18c746014cf24fabca9e1282c52c330476e

![image](https://github.com/user-attachments/assets/07a9e032-fcb3-42e6-80fb-88e851644704)

I hope this does not introduce some weird side effects.

**Comment by boeckmann** [comment]
Great, will test the next days :)
