### ISSUE TITLE
Make DIR aware of 40-columns mode

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/bugz#16]
==== reported by bttr ====

MS-DOS 6.22 COMMAND.COM:

![image](https://github.com/SvarDOS/bugz/assets/9503501/b26220c1-8e33-476b-914c-c487327e6f8f)

1. Look, how it all fits into 39 columns max.
2. MS-DOS command.com uses 'yy' only.
3. And disables usage of thousands separator, when there are < 80 columns available.

![image](https://github.com/SvarDOS/bugz/assets/9503501/07b2e4e4-4c67-43d7-9619-3cbd11eac840)

1. SvarCOM always displays 'yyyy' currently.
2. SvarCOM display is to wide in general, e.g., 'bytes' and 'bytes free' wrap.
3. The summary is 1 too far to the right and thus, the lines breaks.

==== from mateusz ====

> The summary is 1 too far to the right and thus, the lines breaks.

The fields are placed so they allow outputting 10 digits, that is: the maximum length of a 32 bit number, and the last summary line ("xxx bytes free") is placed so the value is aligned consistently with the value above it.

MS-DOS leaves only 9 places for the number of files. Maybe it's a good compromise, at least for 40-columns system, but I wonder what happens when the amount of files reaches 1'000'000'000 - even though it's probably not a concern for the vast majority of users.

==== from bttr ====

> The fields are placed so they allow outputting 10 digits, that is: the maximum length of a 32 bit number, and the last summary line ("xxx bytes free") is placed so the value is aligned consistently with the value above it. 

I see. The root cause is 'Datei(en)' being too long.

Same for 'fichier(s)' in French.

And Google Translate tells me Turkish 'dosya' might be singular only. Plural would be 'dosyalar', which results in 'dosya(lar)' for this topic.

To be honest, 'file(s)' is a bad label, because the number also includes directories. Maybe a relict from when MS-DOS didn't support directories at all.

> MS-DOS leaves only 9 places for the number of files. Maybe it's a good compromise, at least for 40-columns system, but I wonder what happens when the amount of files reaches 1'000'000'000 - even though it's probably not a concern for the vast majority of users. 

I agree. And until SvarCOM supports DIR /S it also doesn't matter in SvarCOM. ;-)

If DIR /S is implemented in SvarCOM, you could just output 999'999'999 and put an additional line showing the real number.

**Comment by mateuszviste** [comment]
apparently I have already implemented this in ver 2022.4

![image](https://github.com/SvarDOS/bugz/assets/9503501/93b41b0b-a08f-4902-a299-ed8ed33aa6da)

**Comment by bttrx** [comment]
I built SvarCOM from 'trunk' today and DIR on 40 columns works fine for me in VirtualBox. :-)
