### ISSUE TITLE
Replace FDISK with FDISK lite on install media

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/bugz#26]
A couple of weeks ago I hacked the FDISK sources so a UI-less FDISK can be built: https://github.com/FDOS/fdisk/pull/37

This issue is about replacing the full-blown FDISK binary on the first installation diskette by the "LITE" version.

Such FDISK is 30% smaller than the UI version (50K vs 72K), hence it would take less space on the install floppies and would be less likely to fail because of out of memory conditions (esp. relevant when running while INSTALL.COM is running).

**Comment by boeckmann** [comment]
Thats a greate idea, if the user can choose from some installation / partitioning options like

1. Select drive to install
2. Select partition to install
   a) use existing partition
   b) wipe disk and create single partition of specified size
   ...

FDISK supports calls like this (wipe disk, create 2000MB primary partition, fill rest with logical):
```
FDISK 1 /CLEARMBR /PRI:2000 /EXT:MAX /LOG:MAX
```

**Comment by mateuszviste** [comment]
on afterthought I do not think this is such a good idea. FDISK is a quite powerful tool. Using it without its UI is not very easy, and covering all its capabilities from within the SvarDOS installer is not realistic (plus it would waste more space than FDISK-LITE saved in the first place). Better to stay with the full-blown FDISK.
The only true advantage of FDISK-LITE would be that it has more chances to work when called from within the SvarDOS installer on very low-memory systems. But this is an issue that should be addressed separately, if it really occurs.
