### ISSUE TITLE
Can't star the "bugz" repository on GitHub because it is empty

### ISSUE THREAD

**Issue by evan** [SvarDOS/bugz#32]
Apparently

**Comment by mateuszviste** [comment]
It is empty, yes, because github is not used as repository. The SvarDOS repository is at svn.svardos.org.
This github account is an empty shell used only for bug tracking.

I will add a formal readme file to the github repo so it is more clear.

**Comment by evan** [comment]
Thank you; now I can star it as a bookmark on GitHub.
