### ISSUE TITLE
pkg will not install a package with a version in the filename

### ISSUE THREAD

**Issue by evan** [SvarDOS/bugz#35]
Some packages from http://svardos.org/?p=repo include a version in the filename, and some do not. If you download an SVP with a version, `pkg` will not install it unless you manually rename it, because the filenames don't match.

It would be nice if `pkg` ignored the version in the filename automatically.

**Comment by mateuszviste** [comment]
the versions in svp filenams are a mishap, they should be there as it makes filenames non-8+3 compatible. A have modified the repo site so it always returns packages with proper 8+3 filenames.
