### ISSUE TITLE
SvarCOM: copy operation fails if destination specifier is drive only

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/bugz#39]
This does not work: `copy abc.txt C:`

the expected behaviour is: copy abc.txt to the current working directory of drive C:

I am not sure if this is a design decision of an oversight, so I report it here.

**Comment by mateuszviste** [comment]
Works fine for me, so I am probably missing something. Could you please provide more details about how I could reproduce the issue?

![image](https://github.com/SvarDOS/bugz/assets/9503501/bcd5ca8a-b12d-4474-b051-31996b7785cf)

**Comment by boeckmann** [comment]
Whatever this was, I can not reproduce it by myself now. Most likely problem was in front of the PC :/

**Comment by mateuszviste** [comment]
Ah, a glitch in the carbon-based processing unit. That happens to me a lot as well. :-)
Closing for now. Should the issue reappear, do not hesitate to reopen.
