### ISSUE TITLE
EDR-DOS kernel

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/bugz#43]
I started doing some work on the EDR-DOS kernel. Shall we put that under version control anywhere? Perhaps as a sub-project under SvarDOS here on Github? At the moment I use a local mercurial repository on my PC, a clone of @ecm-pushbx version. We can also stick to mercurial, but I don't know where to host it.

What I have done so far:
- Create Makefile for DRBIO.SYS (WMAKE)
- Switch to Watcom WLINK instead of WarpLink

The Watcom linked binary is exactly the same as the WarpLink linked. So at the moment I see no problem in using WLINK (but benefits, because it runs on more platforms).

I would like to get rid of at least some proprietary tools used in the build process and replace them by open source versions. For FIXUPP and COMPBIOS, this should be achievable with moderate work. Perhaps COMPBIOS can be dropped altogether, if we get a UPXed DRBIO working. But I have not investigated this yet.

Dropping RASM86 will be hard, but should be a long term goal. I see two options here: re-implement RASM86 or convert the code to JWASM, with a lot of work for both of them.

**Comment by mateuszviste** [comment]
That's super interesting, kudos to you for taking up such challenge!

I have of course no issue with hosting your EDR fork somewhere under the SvarDOS project, be it as a subproject on the github SvarDOS account or directly on svn.svardos.org, whichever you prefer. The only thing about github is that I am not 100% sure the EDR license is compatible with whatever github expects, this would need to be double checked just to be safe.

**Comment by boeckmann** [comment]
While I do not see a license issue with Github I think it is better to play safe. I for the start I will put this on a separate Git server I own. It is not important that the repo is hosted here. I'll put a link here when it is set up.

**Comment by mateuszviste** [comment]
I have read the Github ToS and it appears they are very permissive about what can be hosted. My understanding is that basically as long as we are not breaking any law, it's fine.
https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#c-acceptable-use
https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies

So I do not see any issue to add some "EDR-DOS kernel" repo here. You should now have the necessary rights to do it, should you wish to proceed.

**Comment by boeckmann** [comment]
Many thanks :-)

**Comment by Torinde** [comment]
FYI: https://github.com/the-grue/edrdos

**Comment by boeckmann** [comment]
> FYI: https://github.com/the-grue/edrdos

Thanks for sharing this. It seems this repository is at the moment a plain Git conversion of ecms mercurial repo, missing the latest patches. I'll keep having a look at it, in case that there are some developments we should not miss.

**Comment by mateuszviste** [comment]
closing this one since edr has its own subrepo now
