### ISSUE TITLE
User may forget to remove the install diskette after installation

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/bugz#44]
This ticket is copied from osdn https://osdn.net/projects/svardos/ticket/45426

Reported by Fritz Mueller:

(...) I think I got the problem: It has to do with rebooting the 2,8 MB diskette. I worked with virtualbox. After installation there is a message that you should remove the diskette (it is possible to overread it!), but this cannot be done as virtualbox only offers this when machine is SWITCHED OFF. So after a REBOOT it offers installation again and if you do so you run into problems. And if you go to temp and execute the batch there you can get the message with %DOSDIR%.

There was another message I had there:

config.sys error in line 3

            DEVICE=C:\SVARDOS\BIN\HIMEMX.EXE (of course, because of DOSDIR nothing was installed) and: 

Bad or missing command interpreter: C:\command.com /E:512 /P

So checking if the correct version is already installed or a shutdown to make it possible to remove the diskette or a blinking warning to remove the diskette or something like this could fix the problem.

It is a DAU problem as we call it in german (most possible stupied user problem), but shit happens.

**Comment by mateuszviste** [comment]
This happens when the user forgets to remove the installation disk after setup, reboots, then aborts the newly-loaded installer and tries to execute the post-install script manually.

I am not sure what is the best solution that could be applied here. One way could be checking that a pending post-install script is present and tell the user something like "it appears an unfinished installation is pending on drive C:. To finalize it please remove the installation medium and reboot, or press any key to continue with a new installation"

another approach would be for the installer to verify that the user removed the diskette from the drive before rebooting... but this wouldn't work with the CD installer.

third one would be to make the message "please remove the diskette from drive" much more visible (blinking bright red or so).

**Comment by bttrx** [comment]
> After installation there is a message that you should remove the diskette (it is possible to overread it!), **but this cannot be done as virtualbox only offers this when machine is SWITCHED OFF**.

No problem here with VirtualBox 6.1 on Linux Mint MATE. For a VM executing SvarDOS (or any other DOS) I can just select from the menu "Geräte" -> "Diskettenlaufwerke" -> "Medium entfernen". Afterwards `dir a:` fails (as expected).

**Update:** I wrote similar already at https://osdn.net/projects/svardos/ticket/45426#comment:12510:45426:1661455555

**Comment by bttrx** [comment]
> third one would be to make the message "please remove the diskette from drive" much more visible (blinking bright red or so).

I vote for this approach.

**Comment by mateuszviste** [comment]
I hope this should be good enough.

![image](https://github.com/SvarDOS/bugz/assets/9503501/47876145-a6b0-4cbe-98f3-1b73688b7a1d)
