### ISSUE TITLE
Duplicated kernel.sys file

### ISSUE THREAD

**Issue by igully** [SvarDOS/bugz#45]
I installed [svardos-20231227-floppy-1.44M.zip](http://svardos.org/download/20231227/svardos-20231227-floppy-1.44M.zip) and got a copy of kernel.sys on both the root directory and under /SvarDOS/BIN.

**Comment by boeckmann** [comment]
There are plans to support multiple kernels (FreeDOS, EDR-DOS...)and versions under SvarDOS. So there has to be a place to store backups of the kernels. KERNEL.SYS backup is now in SVARDOS\BIN. But there are discussions about relocating that to SVARDOS\KERNELS\...

**Comment by mateuszviste** [comment]
indeed not really a bug, rather a "future-proof design" :-)

**Comment by igully** [comment]
Ah, I see, it is a placeholder. Thanks for pointing it out.
