### ISSUE TITLE
Cluttered startup screen

### ISSUE THREAD

**Issue by igully** [SvarDOS/bugz#49]
Once you get to boot SvarDOS you get an untidy and excessively cluttered startup screen.

![SVARBOOT](https://github.com/SvarDOS/bugz/assets/50423467/a1511cb7-f2b7-4e81-a135-024bb3a85cfb)

I understand the need to keep disclaimers and lawyers at bay, but the boot screen of SvarDOS is an ugly untidy mess. Can you throw all the legal stuff away from our face please? It is excessive and cannot be configured to disappear in an easy manner, or at the very least kept at bay.

Suggestions:

1) Add an empty/blank line between the legal disclaimer and the actual DOS output (between lines 8 and 9 of the console).

2) Eliminate lines about the legal mumbo jumbo (lines 5 to 8 of the console), and if they still are legally required to appear, place them in a text file so that average users can quickly recover their space by removing them. 

Example of the result of my suggestions applied:

![SVARBOOT2](https://github.com/SvarDOS/bugz/assets/50423467/d3ece726-47b9-4c32-af47-978f2de0b7c3)

**Comment by boeckmann** [comment]
While it annoys me too (I compiled the kernel without this notice for myself), the GPL states the following:

> If the modified program normally reads commands interactively when run, you must cause it, when started running for such interactive use in the most ordinary way, to print or display an announcement including an appropriate copyright notice and a notice that there is no warranty (or else, saying that you provide a warranty) and that users may redistribute the program under these conditions, and telling the user how to view a copy of this License.

So at least in the official distribution sets it is safer to leave this notice in. But this is a FreeDOS kernel thing, so probably it should be discussed further at https://github.com/fdos/kernel. I'd recommend opening an issue there.

**Comment by mateuszviste** [comment]
Indeed, as @boeckmann stated, we are using the FreeDOS kernel and hence we are tied to how the FreeDOS kernel behaves.

The only alternative would be to emit a CLS call in the autoexec.bat, but I do not think it would be wise to do so as it could hide possibly worthy messages from the kernel.

Also please note that there is an ongoing plan of introducing (or even possibly swapping) the kernel used by SvarDOS, so we would/could use the EDR-DOS kernel instead of FreeDOS. The startup screen would be much less cluttered in such event.

In any case, in the current situation there is nothing we can do about these pesky messages.

**Comment by igully** [comment]
Thank you both for your answers. 

FreeDOS is quite a mess in many ways, despite all that it has positively achieved.

A CLS in AUTOEXEC.BAT is not really a solution for the same reasons you pointed out.

I look forward into toying with the EDR-DOS kernel.

It would be interesting to explore the pros and cons of the FreeDOS kernel vs the EDR-DOS kernel, and include the current development pace/status into that comparison.

**Comment by mateuszviste** [comment]
> I look forward into toying with the EDR-DOS kernel.

It is a bit early yet, but you might want to keep an eye on the dedicated project area for EDR-DOS: https://github.com/SvarDOS/edrdos/issues

Bernd is very active there these days and is making outstanding progress. My (very loose) understanding is that currently the EDR-DOS shell is somewhat flaky, but the kernel is robust so it should be possible to get it into a "preview" SvarDOS package soon.
On my side I still have to release a new SvarCOM version with a few compatibility fixes that allow to run SvarCOM atop the EDR-DOS kernel.
