### ISSUE TITLE
config.sys: DOS=HIGH,UMB should be placed below HIMEM.SYS line...

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/bugz#53]
... because of the way the EDR-DOS kernel handles config.sys. The default config.sys (written by the installer?) places DOS=... on the first line of config.sys.

**Comment by bttrx** [comment]
You should fix the EDR-DOS kernel instead. :-D

**Comment by boeckmann** [comment]
@bttrx call you back in a year :-D

**Comment by mateuszviste** [comment]
Took me some 45 seconds to change it, so why not if it makes the EDR kernel happy :)

http://svn.svardos.org/comp.php?repname=SvarDOS&compare[]=%2F@1632&compare[]=%2F@1633
