### ISSUE TITLE
Today's 'bugz' repo fine-tuning

### ISSUE THREAD

**Issue by bttrx** [SvarDOS/bugz#56]
@mateuszviste

I hope you don't mind that I've applied some fine-tuning to this repo.

What I did in detail:

1. For the repository details:
    1. Added website link
    2. Added topics (tags)
    3. Removed the 'Releases', 'Packages', and 'Deployments' links
2. Removed the 'Actions' tab

**Comment by mateuszviste** [comment]
sounds like good ideas, thanks :)
