### ISSUE TITLE
Preferred location for .LNG files

### ISSUE THREAD

**Issue by bttrx** [SvarDOS/bugz#58]
Hi!

If I understand correctly, @mateuszviste moved `.LNG` files for his projects from `%DOSDIR%\NLS` to `%DOSDIR%\BIN` to improve compatibility with MS-DOS 2.0 (http://svardos.org/?p=forum&thread=1691355704). But `FDISK.LNG` is still placed to `%DOSDIR%\NLS`.

Is `%DOSDIR%\BIN` the recommended directory for `.LNG` files now?
Or is this decision left to the developer? (@boeckmann in the case of FDISK)

Cheers,
Robert

**Comment by boeckmann** [comment]
Good question. I will adapt the package if conventions have changed. Did not notice that until now.

**Comment by mateuszviste** [comment]
I have indeed switched away from the %DOSDIR%/NLS location for LNG file at some point. My current preference is "LNG file sits in the same directory as the executable file". The reason for this is that such location makes it easier to load the LNG file: less instructions and less memory required to build the path. This also translates to a smaller DOS environment (if/once all tools use the scheme).

One extra simplification is also that there is no need to support "lists of directories" that could be present in the NLSPATH variable.

SvarLANG makes it possible to use both approaches: NLSPATH (FreeDOS-style) or the minimalist "same as where EXE is" (SvarDOS-style). I do not control what other developers do, but *myself* I will definitely use the SvarDOS-style location.

For comparison - here is the code used for FreeDOS-compatibility NLSPATH support:
http://svn.svardos.org/filedetails.php?repname=SvarDOS&path=%2Fsvarlang.lib%2Ftags%2F20230730%2Fauto_nls.c

And this is the code that loads the LNG file when it is in the same directory as the executable:
http://svn.svardos.org/filedetails.php?repname=SvarDOS&path=%2Fsvarlang.lib%2Ftags%2F20230730%2Fauto_exe.c

**Comment by bttrx** [comment]
Shall we add this recommendation / information somewhere to the SvarDOS documentation, either at [SvarDOS/doc/](http://svn.svardos.org/listing.php?repname=SvarDOS&path=%2Fdoc%2F) or [SvarDOS/help/](http://svn.svardos.org/listing.php?repname=SvarDOS&path=%2Fhelp%2F)?

Otherwise, all has been said, I think, and we can close this issue.

**Comment by mateuszviste** [comment]
> Shall we add this recommendation / information somewhere to the SvarDOS documentation, either at [SvarDOS/doc/](http://svn.svardos.org/listing.php?repname=SvarDOS&path=%2Fdoc%2F) or [SvarDOS/help/](http://svn.svardos.org/listing.php?repname=SvarDOS&path=%2Fhelp%2F)?

I have modified the pkgfmt help to reflect this LNG/NLS convention:

http://svn.svardos.org/diff.php?repname=SvarDOS&path=%2Fhelp%2Fhelp-en%2Fpkgfmt.ama&rev=1663&peg=1663
