### ISSUE TITLE
Dos Navigator ver 1.51 incompatibility with SvarCOM

### ISSUE THREAD

**Issue by bttrx** [SvarDOS/bugz#67]
@mateuszviste

I observed some obscure problem while running 1999 [Dos Navigator (DN) ver 1.51](https://github.com/maximmasiutin/Dos-Navigator) on SvarDOS.

DN is unable to run a program, e.g., `FOO.EXE` or `BAR.COM`, when executed from its file panels by pressing ENTER. User screen always shows `Bad command or file name` instead. But when I type `FOO.EXE` or `BAR.COM` at DN's command line and press ENTER, there is no problem.

The problems persists on MS-DOS 6.22 + SvarCOM 2024.1, but vanishes when using MS `COMMAND.COM` or FreeDOS FreeCom.

With the help of @ecm-pushbx and her great ldebug we could trace the problem down to DN presenting an off-by-one string length byte and two (!) CRs at the end of the command line, which confuses SvarCOM.

Yes, it's a bug in DN, but as it didn't occur with MS-DOS or FreeDOS/FreeCom for the last 30 or more years, a workaround should also be included in SvarCOM.

One solution would be to modify the `parse_argv` function in `command.c`.

Current code:

```c
static void parse_argv(struct config *cfg) {
  const unsigned char *cmdlinelen = (void *)0x80;
  char *cmdline = (void *)0x81;

  memset(cfg, 0, sizeof(*cfg));

  /* set a NULL terminator on cmdline */
  cmdline[*cmdlinelen] = 0;

  while (*cmdline != 0) {
```

Modified code:

```c
static void parse_argv(struct config *cfg) {
  const unsigned char *cmdlinelen = (void *)0x80;
  char *cmdline = (void *)0x81;

  memset(cfg, 0, sizeof(*cfg));

  /* set a NULL terminator on cmdline */
  cmdline[*cmdlinelen] = 0;

  /* workaround a bug in Dos Navigator 1.51 */
  if (*cmdlinelen != 0 && cmdline[*cmdlinelen - 1] == 13) {
    cmdline[*cmdlinelen - 1] = 0;
  }

  while (*cmdline != 0) {
```

A more universal solution would be to loop through `cmdline` and replace the very first CR with 0 to NULL-terminate the string.

Relevant spots in DN source code are at:

- https://github.com/maximmasiutin/Dos-Navigator/blob/master/RUNCMD.INC#L78
- https://github.com/maximmasiutin/Dos-Navigator/blob/master/RUNCMD.INC#L333
- https://github.com/maximmasiutin/Dos-Navigator/blob/master/DN.ASM#L188
- https://github.com/maximmasiutin/Dos-Navigator/blob/master/DN.ASM#L227

**Comment by mateuszviste** [comment]
Interesting, so it basically means the cmdline length at [0x80] cannot be trusted.

Thanks for looking it up, and huge thanks to @ecm-pushbx for your expert help on figuring out the exact cause!

I have committed a fix a few minutes ago:
http://svn.svardos.org/diff.php?repname=SvarDOS&path=%2Fsvarcom%2Ftrunk%2Fcommand.c&rev=1714&peg=1714

It is not exactly the solution that you propose because I do not like having a special hack for DN, but the spirit is similar.
This will be part of version 2024.2, that I will freeze and publish in a few days once I have tested it a bit more just to be sure.

**Comment by boeckmann** [comment]
> I have committed a fix a few minutes ago: http://svn.svardos.org/diff.php?repname=SvarDOS&path=%2Fsvarcom%2Ftrunk%2Fcommand.c&rev=1714&peg=1714

Here is one to think about: What if the length of the command line is 127? :-)

Also, in general, existance of trailing CR and / or null can not be assumed, as described in [1]. This is in german, sadly, so here is the important part, translated to English:

>Most command processors place an ASCII-13 after the PSP command line. Novell DOS 7 COMMAND.COM and 4DOS/NDOS also place an ASCII-0 (probably not with MS-DOS COMMAND.COM). However, this does not happen if the line contains 125 or more characters. When calling via INSTALL= the ASCII-0 is probably also missing with Novelll DOS. MS-DOS 7 sets the length byte to 127 for overlong command lines and places an ASCII-13 ASCII-13 at this position (i.e. the ASCII-13 is then one position too early).  Borland Pascal 7.00 IDE does not set the ASCII-0 (and probably also not the ASCII-13), but an invalid length byte 128...

[1] http://www.antonis.de/dos/dos-tuts/mpdostip/html/msdostip.htm

**Comment by bttrx** [comment]
@boeckmann What a mess this ASCII-0 and ASCII-13 is! :-( Sounds like the spec wasn't clear enough.

**Comment by mateuszviste** [comment]
> Here is one to think about: What if the length of the command line is 127? :-)

yesss, that is one of the things I wanted to double check. all this command-line termination & length declaration is a slightly fuzzy subject with a couple of edge cases. :/

> Also, in general, existance of trailing CR and / or null can not be assumed

I think you are right. So we cannot trust the command-line length at [80h] but yet we have to trust it /a little/. I guess safest would be to consider that the cmdline ends at first CR, 0x00 or at the length declared in [80h], whichever comes first. Will work on a clean patch for this.

> What a mess this ASCII-0 and ASCII-13 is! :-(

It is! But that's part of this archeological game.

**Comment by mateuszviste** [comment]
New patch committed. This variation is even closer to Robert's earlier suggestion than my initial patch, although it is slightly more defensive.

The aggregated patch is this:
http://svn.svardos.org/comp.php?repname=SvarDOS&compare[]=%2Fsvarcom%2Ftrunk%2Fcommand.c@1713&compare[]=%2Fsvarcom%2Ftrunk%2Fcommand.c@1715

Also an interesting link: https://faydoc.tripod.com/structures/13/1378.htm
This one confirms what Matthias Paul mentioned in his german "msdos tips" document about the BP7 bug.

**Comment by ecm-pushbx** [comment]
I wrote about the debugging we did to find out about the wrong DN command line: https://pushbx.org/ecm/dokuwiki/blog/pushbx/2024/0214_remote_debugging_of_svarcom_and_dos_navigator_incompatibility

**Comment by bttrx** [comment]
Successfully tested on MS-DOS 6.22 + 'trunk' SvarCOM + 1999 DN. :-)
