### ISSUE TITLE
COPY doesn't preserve timestamps

### ISSUE THREAD

**Issue by bttrx** [SvarDOS/bugz#69]
(It never did in SvarCOM so far.)

**Comment by mateuszviste** [comment]
shortly said:

````COPY A.TXT B.TXT````   -->   clones the timestamps of A.TXT to B.TXT
````COPY A.TXT+B.TXT C.TXT````  -->  timestamp of C.TXT is set to current date/time

**Comment by bttrx** [comment]
Tested now: Works for me! :1st_place_medal:
