### ISSUE TITLE
pkgnet pull XXX+N -> 'package not found on server'

### ISSUE THREAD

**Issue by bttrx** [SvarDOS/bugz#76]
I'm running pkgnet ver 20240201 and I'm unable to download packages numbered like, e.g., `sved-2024.0+1`, `sved-2023.5+1`, or `acrodos-1.0+1.svp` from the repo. But `pkgnet search PACKAGE` lists these versions.

**Comment by mateuszviste** [comment]
Fixed now:

![image](https://github.com/SvarDOS/bugz/assets/9503501/7db318f1-76eb-44e6-b286-de1efd293bdf)

patch at http://svn.svardos.org/diff.php?repname=SvarDOS&path=%2Fwebsite%2Frepo%2Findex.php&rev=1791&peg=1791
