### ISSUE TITLE
Wrong build string when using svardos-usb.img

### ISSUE THREAD

**Issue by bttrx** [SvarDOS/bugz#79]
1. Installer screen "Welcome to SvarDOS" displays "SvarDOS" in the upper right corner, but it should read "20240414".
2. Execution of POSTINST.BAT displays: `INSTALLING SVARDOS BUILD SVARDOS`, but it should read `INSTALLING SVARDOS BUILD 20240414`.
3. Execution of POSTINST.BAT displays `SvarDOS (build SVARDOS) has been installed.`, but it should read: `SvarDOS (build 20240414) has been installed.`

This is caused by the volume label in [boot-svardos.img](http://svn.svardos.org/filedetails.php?repname=SvarDOS&path=%2Ffiles%2Fboot-svardos.img) being `SVARDOS`.

**Comment by mateuszviste** [comment]
All true and exact, yes. I think the easiest solution would be that build.sh overwrites the label of the boot-svardos.img file using mlabel.

**Comment by bttrx** [comment]
I already tried mlabel before submitting my report, but:

```
$ mlabel -i boot-svardos.img -s
init :: non DOS media
Cannot initialize '::'
mlabel: Cannot initialize drive
```

I never used mlabel before, so I don't know, what I'm doing here. ;-)

**Comment by mateuszviste** [comment]
I think that you need to (somehow) tell mlabel to look at offset 512 to find the filesystem (ie. skip the MBR).

**Comment by mateuszviste** [comment]
The FS is actually not located in the second sector, which makes it a little bit trickier. Here you go:

![image](https://github.com/SvarDOS/bugz/assets/9503501/7c8777bd-f185-43d8-806a-de433b976fcc)

**Comment by bttrx** [comment]
I see. 32256 comes from start sector 63 * sector size 512.

Fixed by commit [WebSVN – SvarDOS – Diff – Rev 1808 and 1772 – /build.sh](http://svn.svardos.org/diff.php?repname=SvarDOS&path=%2Fbuild.sh&rev=1808&peg=1808) and tested by myself for "bleeding edge" [build 20240415](http://www.svardos.org/?p=files&dir=20240415).
