### ISSUE TITLE
Webserver still delivers old kernel.svp package

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/bugz#83]
I created a new packages kernel-2042+1.svp which does not contain SYS.COM anymore. The webserver still delivers the old package. I then renamed the old package to kernel-2042.svp in hope that this package gets superseeded by kernel-2042+1.svp. But it did not help. Is kernel.svp handled special?

**Comment by mateuszviste** [comment]
No special handling, no. The version inside the filename does not matter much, it's the LSM that counts and it seems you forgot to update the version in the LSM :)
