### ISSUE TITLE
SvarCOM / EDR critical error handler not working?

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/bugz#86]
When trying to change to a non-ready drive A:, normally the critical error handler asks the user what to do (Abort, Retry etc.). However I noticed the following under SvarCOM / EDR:
<img width="316" alt="Bildschirmfoto 2024-07-27 um 09 28 44" src="https://github.com/user-attachments/assets/203e4d72-186d-46f9-8818-fd8979bdbd93">

I double-checked with the EDR kernel and EDR-COMMAND. This shows correct behaviour:
<img width="288" alt="Bildschirmfoto 2024-07-27 um 09 32 18" src="https://github.com/user-attachments/assets/2391d690-a7ca-40bb-ae7f-735635534ac0">

Have not checked the SvarCOM / FreeDOS kernel combo yet.

**Comment by mateuszviste** [comment]
Duplicate of #24

**Comment by boeckmann** [comment]
Oh, sorry!

**Comment by mateuszviste** [comment]
no worries, #24 is not very descriptive in the first place :) the int 24 handler is one of the two major things that are left to do in SvarCOM (the other being DIR /S support).
