### ISSUE TITLE
EDR-specific boot protocol

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/bugz#88]
The EDR kernel loads command.com differently  than the FreeDOS kernel. SvarCOM should be able to detect the EDR kernel and figure out:
- Is it init time? If yes:
- Was F5 pressed? If not:
- Was F8 pressed? If not then execute autoexec.bat, if yes execute it step by step

Bernd provides valuable hints about EDR detection here: https://github.com/SvarDOS/edrdos/issues/83

**Comment by mateuszviste** [comment]
implemented in 2024.4 (to be released)

**Comment by mateuszviste** [comment]
> implemented in 2024.4 (to be released)

released today and integrated right away within bleeding edge.

**Comment by boeckmann** [comment]
Great, shall I put the current kernel rev. also into the package repository? Should work better than the older one...

**Comment by mateuszviste** [comment]
> Great, shall I put the current kernel rev. also into the package repository? Should work better than the older one...

sure, feel free to do it whenever you feel the version you have is reasonably safe :-)
