### ISSUE TITLE
EDR-compat: make the master environment inherit env variables set in CONFIG.SYS

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/bugz#92]
It is possible to set env variables in CONFIG.SYS with EDR-DOS. It would be nice to have these variables land in SvarCOM's master environment.
SvarCOM is already accessing the EDR config environment for F5/F8 detection, so this could be a next step.
Lots of technical information in https://github.com/SvarDOS/edrdos/issues/83

**Comment by boeckmann** [comment]
COMSPEC is now provided by the kernel through the config environment.

**Comment by mateuszviste** [comment]
Awesome! Is the config environment at seg 60h now? This will make it much easier for SvarCOM to use it (because it will not be overwritten by SvarCOM's resident code itself)

**Comment by boeckmann** [comment]
Not yet. This will be the next thing I implement...

**Comment by boeckmann** [comment]
> Is the config environment at seg 60h now?

Yes, copied now. A memory dump of seg 60 confirms COMSPEC is present. The segment in private data area should also be updated to 60h, though I did not verify this yet.

**Comment by mateuszviste** [comment]
Very cool! This made it much easier to pull in the config environment since I do not have to worry about it being randomly overwritten. Attached the svarcom build that uses config env to initialize its master env.
[svarcom-2024.4 beta 2.zip](https://github.com/user-attachments/files/16575896/svarcom-2024.4.beta.2.zip)

**Comment by mateuszviste** [comment]
[svn commit](http://svn.svardos.org/diff.php?repname=SvarDOS&path=%2Fsvarcom%2Ftrunk%2Fcommand.c&rev=1861&peg=1861)

**Comment by mateuszviste** [comment]
I am checking here if the config environment lives at seg 0x60, and use it only at this condition. This will avoid crashes under earlier versions of the EDR kernel (or DR-DOS) where the environment could be overwritten before SvarCOM copies it.

**Comment by boeckmann** [comment]
Perfect. Will try it out tomorrow :)
